# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-06 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('src', models.CharField(max_length=200)),
                ('sales', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=5)),
            ],
        ),
    ]
