# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-10 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=9999.0),
        ),
    ]
