# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-14 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0002_menu_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '餐品', 'verbose_name_plural': '餐品'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=9999.0, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.FloatField(default=5, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='typeName',
            field=models.CharField(max_length=50, verbose_name='种类'),
        ),
    ]
