# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0003_auto_20190514_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='src',
            field=models.ImageField(blank=True, default='image/defaultImg.jpg', upload_to='image', verbose_name='图片'),
        ),
    ]
