# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-17 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0006_menu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('启用', '启用'), ('female', '不启用')], default='启用', max_length=30, verbose_name='是否启用'),
        ),
    ]
