# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-19 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0007_auto_20190517_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('启用', '启用'), ('停用', '停用')], default='启用', max_length=30, verbose_name='是否启用'),
        ),
    ]
