# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-06 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('food_id', models.IntegerField()),
                ('food_name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=5)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('numb', models.IntegerField(default=0)),
            ],
        ),
    ]
