# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190507_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('food_id', models.IntegerField()),
                ('food_name', models.CharField(max_length=50)),
                ('numb', models.IntegerField(default=0)),
            ],
        ),
    ]
