# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-07 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_todayorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayorder',
            name='state',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
