# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-07 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_todayorder_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayorder',
            name='state',
            field=models.CharField(default='未完成', max_length=20),
        ),
    ]
