# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-07 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190507_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todayorder',
            name='date',
        ),
        migrations.AddField(
            model_name='todayorder',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
