# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-09 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190507_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='open_id',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food_id',
        ),
    ]
