# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-09 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190509_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=200),
        ),
    ]
