# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-10 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190509_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '所有订单', 'verbose_name_plural': '所有订单'},
        ),
        migrations.AlterModelOptions(
            name='todayorder',
            options={'verbose_name': '每日订单', 'verbose_name_plural': '每日订单'},
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=9999.0, verbose_name='订单总价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food_name',
            field=models.CharField(max_length=50, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=200, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='score',
            field=models.IntegerField(default=5, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=20, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='todayorder',
            name='date_time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='todayorder',
            name='food_name',
            field=models.CharField(max_length=50, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='todayorder',
            name='number',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='todayorder',
            name='state',
            field=models.CharField(default='未完成', max_length=20, verbose_name='状态'),
        ),
    ]
