# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-19 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190510_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todayorder',
            options={'verbose_name': '每日订单汇总', 'verbose_name_plural': '每日订单汇总'},
        ),
    ]
